#!/bin/sh
# HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=1000000
SAVEHIST=1000000
export PATH="/usr/local/bin:$PATH"
export JAVA_HOME=/usr/lib/jvm/amazon-corretto-17.0.7.7.1-linux-x64
export PATH=$JAVA_HOME/bin:$PATH

export PATH="$HOME/.local/bin":$PATH
# export MANPAGER='nvim +Man!'
export MANWIDTH=999
export PATH=$HOME/.cargo/bin:$PATH
export PATH=$HOME/.local/share/go/bin:$PATH
export GOPATH=$HOME/.local/share/go
export PATH=$HOME/.fnm:$PATH
export GOPATH=$HOME/go 
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:$GOPATH/bin:/usr/local/go/bin
export PATH=$HOME/julia-1.7.3/bin:$PATH
# export PATH=$HOME/node_modules/.bin:$PATH
export PATH=$PATH:$HOME/bin
export PATH=$PATH:$HOME/./rust_modules/bin
# export PATH=$PATH:$HOME/.local/lib/python3.11/site-packages


# export PATH=usr/bin/pip3:$PATH
# eval "$(fnm env)"
# eval "$(zoxide init zsh)"
#eval "`pip3 completion --zsh`"
compctl -K _pip_completion pip3


# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$("$HOME/.miniconda/bin/conda" 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "$HOME/.miniconda/etc/profile.d/conda.sh" ]; then
        . "$HOME/.miniconda/etc/profile.d/conda.sh"
    else
        export PATH="$HOME/.miniconda/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

